package cn.edu.bupt.map.entity;

public class Patroltrack {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patroltrack.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patroltrack.tenantId
     *
     * @mbggenerated
     */
    private Integer tenantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patroltrack.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patroltrack.pipeColor
     *
     * @mbggenerated
     */
    private String pipecolor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patroltrack.pipeType
     *
     * @mbggenerated
     */
    private String pipetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patroltrack.pipeWidth
     *
     * @mbggenerated
     */
    private Double pipewidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patroltrack.createdAt
     *
     * @mbggenerated
     */
    private Long createdat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patroltrack.updatedAt
     *
     * @mbggenerated
     */
    private Long updatedat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patroltrack.version
     *
     * @mbggenerated
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patroltrack.drawPoint
     *
     * @mbggenerated
     */
    private String drawpoint;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patroltrack.id
     *
     * @return the value of patroltrack.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patroltrack.id
     *
     * @param id the value for patroltrack.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patroltrack.tenantId
     *
     * @return the value of patroltrack.tenantId
     *
     * @mbggenerated
     */
    public Integer getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patroltrack.tenantId
     *
     * @param tenantid the value for patroltrack.tenantId
     *
     * @mbggenerated
     */
    public void setTenantid(Integer tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patroltrack.name
     *
     * @return the value of patroltrack.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patroltrack.name
     *
     * @param name the value for patroltrack.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patroltrack.pipeColor
     *
     * @return the value of patroltrack.pipeColor
     *
     * @mbggenerated
     */
    public String getPipecolor() {
        return pipecolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patroltrack.pipeColor
     *
     * @param pipecolor the value for patroltrack.pipeColor
     *
     * @mbggenerated
     */
    public void setPipecolor(String pipecolor) {
        this.pipecolor = pipecolor == null ? null : pipecolor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patroltrack.pipeType
     *
     * @return the value of patroltrack.pipeType
     *
     * @mbggenerated
     */
    public String getPipetype() {
        return pipetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patroltrack.pipeType
     *
     * @param pipetype the value for patroltrack.pipeType
     *
     * @mbggenerated
     */
    public void setPipetype(String pipetype) {
        this.pipetype = pipetype == null ? null : pipetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patroltrack.pipeWidth
     *
     * @return the value of patroltrack.pipeWidth
     *
     * @mbggenerated
     */
    public Double getPipewidth() {
        return pipewidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patroltrack.pipeWidth
     *
     * @param pipewidth the value for patroltrack.pipeWidth
     *
     * @mbggenerated
     */
    public void setPipewidth(Double pipewidth) {
        this.pipewidth = pipewidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patroltrack.createdAt
     *
     * @return the value of patroltrack.createdAt
     *
     * @mbggenerated
     */
    public Long getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patroltrack.createdAt
     *
     * @param createdat the value for patroltrack.createdAt
     *
     * @mbggenerated
     */
    public void setCreatedat(Long createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patroltrack.updatedAt
     *
     * @return the value of patroltrack.updatedAt
     *
     * @mbggenerated
     */
    public Long getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patroltrack.updatedAt
     *
     * @param updatedat the value for patroltrack.updatedAt
     *
     * @mbggenerated
     */
    public void setUpdatedat(Long updatedat) {
        this.updatedat = updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patroltrack.version
     *
     * @return the value of patroltrack.version
     *
     * @mbggenerated
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patroltrack.version
     *
     * @param version the value for patroltrack.version
     *
     * @mbggenerated
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patroltrack.drawPoint
     *
     * @return the value of patroltrack.drawPoint
     *
     * @mbggenerated
     */
    public String getDrawpoint() {
        return drawpoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patroltrack.drawPoint
     *
     * @param drawpoint the value for patroltrack.drawPoint
     *
     * @mbggenerated
     */
    public void setDrawpoint(String drawpoint) {
        this.drawpoint = drawpoint == null ? null : drawpoint.trim();
    }

    @Override
    public String toString() {

        final StringBuilder sb = new StringBuilder("{");
        sb.append("\"id\":")
                .append(id);
        sb.append(",\"tenantid\":")
                .append(tenantid);
        sb.append(",\"name\":\"")
                .append(name).append('\"');
        sb.append(",\"pipecolor\":\"")
                .append(pipecolor).append('\"');
        sb.append(",\"pipetype\":\"")
                .append(pipetype).append('\"');
        sb.append(",\"pipewidth\":")
                .append(pipewidth);
        sb.append(",\"createdat\":\"")
                .append(createdat).append('\"');
        sb.append(",\"updatedat\":\"")
                .append(updatedat).append('\"');
        sb.append(",\"version\":")
                .append(version);
        sb.append(",\"drawpoint\":")
                .append(drawpoint);
        sb.append('}');

        return sb.toString();

    }
}