package cn.edu.bupt.map.entity;

public class Sites {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sites.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sites.tenantId
     *
     * @mbggenerated
     */
    private Integer tenantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sites.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sites.longtitude
     *
     * @mbggenerated
     */
    private Double longtitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sites.latitude
     *
     * @mbggenerated
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sites.sceneUrl
     *
     * @mbggenerated
     */
    private String sceneurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sites.compressStatus
     *
     * @mbggenerated
     */
    private Boolean compressstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sites.ossStatus
     *
     * @mbggenerated
     */
    private Boolean ossstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sites.devicesModelCount
     *
     * @mbggenerated
     */
    private Integer devicesmodelcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sites.sceneModelLoca
     *
     * @mbggenerated
     */
    private String scenemodelloca;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sites.createdAt
     *
     * @mbggenerated
     */
    private Long createdat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sites.updatedAt
     *
     * @mbggenerated
     */
    private Long updatedat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sites.version
     *
     * @mbggenerated
     */
    private Long version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sites.id
     *
     * @return the value of sites.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sites.id
     *
     * @param id the value for sites.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sites.tenantId
     *
     * @return the value of sites.tenantId
     *
     * @mbggenerated
     */
    public Integer getTenantid() {
        return tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sites.tenantId
     *
     * @param tenantid the value for sites.tenantId
     *
     * @mbggenerated
     */
    public void setTenantid(Integer tenantid) {
        this.tenantid = tenantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sites.name
     *
     * @return the value of sites.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sites.name
     *
     * @param name the value for sites.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sites.longtitude
     *
     * @return the value of sites.longtitude
     *
     * @mbggenerated
     */
    public Double getLongtitude() {
        return longtitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sites.longtitude
     *
     * @param longtitude the value for sites.longtitude
     *
     * @mbggenerated
     */
    public void setLongtitude(Double longtitude) {
        this.longtitude = longtitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sites.latitude
     *
     * @return the value of sites.latitude
     *
     * @mbggenerated
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sites.latitude
     *
     * @param latitude the value for sites.latitude
     *
     * @mbggenerated
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sites.sceneUrl
     *
     * @return the value of sites.sceneUrl
     *
     * @mbggenerated
     */
    public String getSceneurl() {
        return sceneurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sites.sceneUrl
     *
     * @param sceneurl the value for sites.sceneUrl
     *
     * @mbggenerated
     */
    public void setSceneurl(String sceneurl) {
        this.sceneurl = sceneurl == null ? null : sceneurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sites.compressStatus
     *
     * @return the value of sites.compressStatus
     *
     * @mbggenerated
     */
    public Boolean getCompressstatus() {
        return compressstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sites.compressStatus
     *
     * @param compressstatus the value for sites.compressStatus
     *
     * @mbggenerated
     */
    public void setCompressstatus(Boolean compressstatus) {
        this.compressstatus = compressstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sites.ossStatus
     *
     * @return the value of sites.ossStatus
     *
     * @mbggenerated
     */
    public Boolean getOssstatus() {
        return ossstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sites.ossStatus
     *
     * @param ossstatus the value for sites.ossStatus
     *
     * @mbggenerated
     */
    public void setOssstatus(Boolean ossstatus) {
        this.ossstatus = ossstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sites.devicesModelCount
     *
     * @return the value of sites.devicesModelCount
     *
     * @mbggenerated
     */
    public Integer getDevicesmodelcount() {
        return devicesmodelcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sites.devicesModelCount
     *
     * @param devicesmodelcount the value for sites.devicesModelCount
     *
     * @mbggenerated
     */
    public void setDevicesmodelcount(Integer devicesmodelcount) {
        this.devicesmodelcount = devicesmodelcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sites.sceneModelLoca
     *
     * @return the value of sites.sceneModelLoca
     *
     * @mbggenerated
     */
    public String getScenemodelloca() {
        return scenemodelloca;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sites.sceneModelLoca
     *
     * @param scenemodelloca the value for sites.sceneModelLoca
     *
     * @mbggenerated
     */
    public void setScenemodelloca(String scenemodelloca) {
        this.scenemodelloca = scenemodelloca == null ? null : scenemodelloca.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sites.createdAt
     *
     * @return the value of sites.createdAt
     *
     * @mbggenerated
     */
    public Long getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sites.createdAt
     *
     * @param createdat the value for sites.createdAt
     *
     * @mbggenerated
     */
    public void setCreatedat(Long createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sites.updatedAt
     *
     * @return the value of sites.updatedAt
     *
     * @mbggenerated
     */
    public Long getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sites.updatedAt
     *
     * @param updatedat the value for sites.updatedAt
     *
     * @mbggenerated
     */
    public void setUpdatedat(Long updatedat) {
        this.updatedat = updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sites.version
     *
     * @return the value of sites.version
     *
     * @mbggenerated
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sites.version
     *
     * @param version the value for sites.version
     *
     * @mbggenerated
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    @Override
    public String toString() {

        final StringBuilder sb = new StringBuilder("{");
        sb.append("\"id\":")
                .append(id);
        sb.append(",\"tenantid\":")
                .append(tenantid);
        sb.append(",\"name\":\"")
                .append(name).append('\"');
        sb.append(",\"longtitude\":")
                .append(longtitude);
        sb.append(",\"latitude\":")
                .append(latitude);
        sb.append(",\"sceneurl\":\"")
                .append(sceneurl).append('\"');
        sb.append(",\"compressstatus\":\"")
                .append(compressstatus).append('\"');
        sb.append(",\"ossstatus\":\"")
                .append(ossstatus).append('\"');
        sb.append(",\"devicesmodelcount\":")
                .append(devicesmodelcount);
        sb.append(",\"scenemodelloca\":\"")
                .append(scenemodelloca).append('\"');
        sb.append(",\"createdat\":\"")
                .append(createdat).append('\"');
        sb.append(",\"updatedat\":\"")
                .append(updatedat).append('\"');
        sb.append(",\"version\":")
                .append(version);
        sb.append('}');

        return sb.toString();

    }
}