package cn.edu.bupt.map.mapper;

import cn.edu.bupt.map.entity.Patroltrack;

import java.util.List;

public interface PatroltrackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patroltrack
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patroltrack
     *
     * @mbggenerated
     */
    int insert(Patroltrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patroltrack
     *
     * @mbggenerated
     */
    int insertSelective(Patroltrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patroltrack
     *
     * @mbggenerated
     */
    Patroltrack selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patroltrack
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Patroltrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patroltrack
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Patroltrack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patroltrack
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Patroltrack record);

    List<Patroltrack> selectAll();
}