package cn.edu.bupt.map.mapper;

import cn.edu.bupt.map.entity.Pipe;

public interface PipeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pipe
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pipe
     *
     * @mbggenerated
     */
    int insert(Pipe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pipe
     *
     * @mbggenerated
     */
    int insertSelective(Pipe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pipe
     *
     * @mbggenerated
     */
    Pipe selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pipe
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Pipe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pipe
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Pipe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pipe
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Pipe record);
}