package cn.edu.bupt.map.mapper;

import cn.edu.bupt.map.entity.Sites;

import java.util.List;

public interface SitesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sites
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sites
     *
     * @mbggenerated
     */
    int insert(Sites record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sites
     *
     * @mbggenerated
     */
    int insertSelective(Sites record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sites
     *
     * @mbggenerated
     */
    Sites selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sites
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Sites record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sites
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sites record);

    List<Sites> selectAll();
}