package cn.edu.bupt.map.mapper;

import cn.edu.bupt.map.entity.Warning;

import java.util.List;

public interface WarningMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning
     *
     * @mbggenerated
     */
    int insert(Warning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning
     *
     * @mbggenerated
     */
    int insertSelective(Warning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning
     *
     * @mbggenerated
     */
    Warning selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Warning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Warning record);

    List<Warning> selectAll();}